### ISSUE TITLE
Sadmin auth fails if ~/.cache directory does not exist.

### ISSUE THREAD

**Issue by thomasmoelhave** [antialize/simple-admin#25]
```
thomasm@bean:~$ sadmin auth
Password for thomasm:
One time password: 
Traceback (most recent call last):
  File "/usr/bin/sadmin", line 891, in <module>
    main()
  File "/usr/bin/sadmin", line 864, in main
    asyncio.get_event_loop().run_until_complete(main_auth(args.user))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/bin/sadmin", line 109, in main_auth
    await prompt_auth(c, user)
  File "/usr/bin/sadmin", line 141, in prompt_auth
    await login(c, user, pwd, otp)
  File "/usr/bin/sadmin", line 80, in login
    with open(c.cookieFile, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/thomasm/.cache/simple_admin_cookie'
```
I created `~/.cache` manually with `mkdir` and all was well.

**Comment by antialize** [comment]
This was fixed in the rust conversion.
